### ISSUE TITLE
Make .gitignore more robust

### ISSUE THREAD

**Issue by rcass** [Alex-Paydarfar/Instanews-App#1]
The gitignore is off to a good start but it is not robust enough and not ignoring all the possible files you don't want saved to your project.

Here is a sample .gitignore that I posted previously:
```
# Ignore OS files #
# =============== #
.DS_Store
.DS_Store?
.vscode/
._*
.Spotlight-V100
.Trashes
ehthumbs.db
*[Tt]humbs.db
*.Trashes

# Ignore packages #
# =============== #
*.7z
*.dmg
*.gz
*.iso
*.jar
*.rar
*.tar
*.zip

# Ignore packages #
# =============== #
node_modules/

# Ignore API Keys
# 

 apikeys
```

- [x] Update .gitignore with the snippet above

**Comment by Github-Commander** [comment]
Ok. I will implement the necessary changes to my .gitignore file.

**Comment by rcass** [comment]
Okay! Just close this issue once you have updated your .gitignore with the snippet mentioned :) 👍

**Comment by rcass** [comment]
Sweet! All looks good 🎉
